# Generated by Django 5.0.1 on 2024-01-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_pereshhabler',
            new_name='is_perishable',
        ),
    ]
