# Generated by Django 5.0.1 on 2024-01-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_suppliers_productinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
